# action.yml
name: 'Api deployment with mvn'
description: 'Action para desplegar apis mediante mvn, también utiliza apim-cli para realizar un get en el api manager.'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'upload'
  color: 'white'
inputs:
  user:  # Usuario Azure 
    description: 'Usuario azure'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}