# action.yml
name: 'Az Artifacts Universal Download'
description: 'Action para la descarga de un artefacto del repositorio de artefactos de Azure DevOps'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'download-cloud'
  color: 'white'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you Anthony'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}