# action.yml
name: 'Az Artifacts Universal Download'
description: 'Action para la descarga de un artefacto del repositorio de artefactos de Azure DevOps'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'download-cloud'
  color: 'white'
inputs:
  user:  # Usuario Azure 
    description: 'Usuario azure'
    required: true
  pass:
    description: 'Contraseña del usuario'
    required: true
  organization: 
    description: 'Organización del artefacto'
    required: true
  project: 
    description: 'Proyecto del artefacto'
    required: true
  feed:
    description: 'Nombre del repositorio de artefacto'
    required: true
  name:
    description: 'Nombre del artefacto'
    required: true
  version:
    description: 'versión del artefacto'
    required: true
    default: 0.0.0
  path:
    description: 'path del artefacto'
    required: true
    default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.pass }}
    - ${{ inputs.organization }}
    - ${{ inputs.project }}
    - ${{ inputs.feed }}
    - ${{ inputs.name }}
    - ${{ inputs.version }}
    - ${{ inputs.path }}