# action.yml
name: 'Az Artifacts Universal Download'
description: 'Action para la descarga de un artefacto del repositorio de artefactos de Azure DevOps'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'download-cloud'
  color: 'white'
inputs:
  user:  # user azure
    description: 'Usuario azure'
    required: true
  pass:  # password user azure
    description: 'Contraseña del usuario'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.pass }}